CREATE TABLE IF NOT EXISTS preferences (
    preference_id INT PRIMARY KEY AUTO_INCREMENT,
    smoking_allowed BOOLEAN DEFAULT TRUE,
    pet_allowed BOOLEAN DEFAULT TRUE,
    user_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);