server {
    listen 80;
    server_name localhost;

    # FRONTEND SPA
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # BACKEND PHP API
    location /api/ {
        # IMPORTANT : root (et PAS alias)
        root /var/www/html;

        # Essaye register, puis register.php
        try_files $uri $uri.php =404;

        include fastcgi_params;
        fastcgi_pass php:9000;

        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    client_max_body_size 20M;
}
